# Generated by Django 3.1.5 on 2022-06-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0018_auto_20220619_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_per_quiz', models.IntegerField(default=1)),
                ('Timer_per_quiz', models.TimeField()),
                ('Total_access_duration', models.IntegerField(default=30)),
                ('training', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Quiz', to='training.training')),
            ],
        ),
    ]
