# Generated by Django 3.1.5 on 2022-06-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(blank=True, help_text='Ignore. Autogenerate by server!', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(blank=True, help_text='Ignore. Autogenerate by server!', max_length=100),
        ),
    ]
