# Generated by Django 3.1.5 on 2022-06-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20220619_1557'),
        ('quiz', '0005_quesmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuesModel',
            new_name='Question',
        ),
    ]
