# Generated by Django 3.1.5 on 2022-06-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_auto_20220619_1557'),
        ('quiz', '0006_auto_20220619_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='training.training'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Question_per_quiz',
            field=models.IntegerField(default=6, help_text='Enter time in minutes'),
        ),
    ]
