# Generated by Django 3.1.5 on 2022-06-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220620_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Question_per_quiz',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Timer_per_quiz',
            field=models.IntegerField(default=60, help_text='Enter time in minutes'),
        ),
    ]
