# Generated by Django 3.1.5 on 2022-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20220620_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Total_access_duration',
            field=models.IntegerField(default=30, help_text='Enter duration in days'),
        ),
    ]
