# Generated by Django 3.1.5 on 2022-06-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20220620_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Username',
        ),
    ]
