# Generated by Django 3.1.5 on 2022-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20220705_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Quiz',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer_Description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='Option_4',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
