# Generated by Django 3.1.5 on 2022-07-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20220706_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Quiz',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Quiz1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Quiz2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Quiz3',
            field=models.BooleanField(default=False),
        ),
    ]
