# Generated by Django 3.1.5 on 2022-07-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_auto_20220706_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz1',
            field=models.BooleanField(),
        ),
    ]
