# Generated by Django 3.1.5 on 2022-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20220706_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Instruction',
            field=models.TextField(default='Add instructions here'),
        ),
    ]
