# Generated by Django 3.1.5 on 2022-07-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_userprofile_quiz1_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Quiz2_response',
            field=models.TextField(default='', null=True),
        ),
    ]
