# Generated by Django 3.1.5 on 2022-07-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_userprofile_quiz3_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz1_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz2_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz3_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
