# Generated by Django 3.1.5 on 2022-07-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_auto_20220709_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Quiz1_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Quiz2_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
