# Generated by Django 3.1.5 on 2022-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_auto_20220709_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz1_score',
            new_name='Quiz_1_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz2_score',
            new_name='Quiz_2_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz3_score',
            new_name='Quiz_3_Score',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz2',
            field=models.BooleanField(default=False, verbose_name='Activate Quiz 2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz3',
            field=models.BooleanField(default=False, verbose_name='Activate Quiz 3'),
        ),
    ]
