# Generated by Django 3.1.5 on 2022-07-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0030_auto_20220709_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_1_Score',
            new_name='Quiz1_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_2_Score',
            new_name='Quiz2_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_3_Score',
            new_name='Quiz3_Score',
        ),
    ]
