# Generated by Django 3.1.5 on 2022-07-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_auto_20220709_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz1_response',
            new_name='Quiz_1_Response',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz1_Score',
            new_name='Quiz_1_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz2_response',
            new_name='Quiz_2_Response',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz2_Score',
            new_name='Quiz_2_Score',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz3_response',
            new_name='Quiz_3_Response',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz3_Score',
            new_name='Quiz_3_Score',
        ),
    ]
