# Generated by Django 3.1.5 on 2022-07-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_auto_20220709_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz1',
            new_name='Quiz_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz2',
            new_name='Quiz_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz3',
            new_name='Quiz_3',
        ),
    ]
