# Generated by Django 3.1.5 on 2022-07-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_auto_20220709_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_1',
            new_name='Quiz1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_1_Response',
            new_name='Quiz1_response',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_2',
            new_name='Quiz2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_2_Response',
            new_name='Quiz2_response',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_3',
            new_name='Quiz3',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Quiz_3_Response',
            new_name='Quiz3_response',
        ),
    ]
