# Generated by Django 3.1.5 on 2022-07-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_auto_20220709_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_1_Score',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
