# Generated by Django 3.1.5 on 2022-07-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_auto_20220709_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(default='question_file', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_1_Score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
