# Generated by Django 3.1.5 on 2022-07-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0036_auto_20220714_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='file',
        ),
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(default='question_file', upload_to=''),
        ),
    ]
