# Generated by Django 3.1.5 on 2022-07-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_auto_20220714_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Option_5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='Option_6',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
