# Generated by Django 3.1.5 on 2022-07-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0043_auto_20220717_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_1_Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_2_Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_3_Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
