# Generated by Django 3.1.5 on 2022-07-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0044_auto_20220717_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Link',
            field=models.CharField(default='mock-quiz/account/', max_length=100),
        ),
    ]
