# Generated by Django 3.1.5 on 2022-07-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0045_userprofile_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Link',
            new_name='Dashboard_Link',
        ),
    ]
