# Generated by Django 3.1.5 on 2022-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0046_auto_20220717_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Dashboard_Link',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Instruction',
            field=models.TextField(default='Add Quiz Instructions here'),
        ),
    ]
