# Generated by Django 3.1.5 on 2022-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0048_auto_20220718_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(default='training_name.csv', help_text='Upload only CSV file with a nanme training_name.csv. Eg PMP.csv', upload_to=''),
        ),
    ]
