# Generated by Django 3.1.5 on 2022-07-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0049_auto_20220718_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Question_per_quiz',
            field=models.IntegerField(default=1, help_text='Number of questions for each training quiz'),
        ),
    ]
