# Generated by Django 3.1.5 on 2022-07-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0050_auto_20220718_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Ques_No',
            field=models.CharField(help_text='Enter name as "trainingName No" eg. PMP1, DASM2', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
