# Generated by Django 3.1.5 on 2022-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0052_auto_20220718_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Number_of_Quiz',
            field=models.IntegerField(default=1, help_text='Enter number of quizzes to assign. Max num = 3'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz1',
            field=models.BooleanField(default=False, help_text='Click it to enable the Quiz1', verbose_name='Activate Quiz 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz2',
            field=models.BooleanField(default=False, help_text='Click it to enable the Quiz1', verbose_name='Activate Quiz 2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz3',
            field=models.BooleanField(default=False, help_text='Click it to enable the Quiz1', verbose_name='Activate Quiz 3'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_1_Score',
            field=models.IntegerField(blank=True, default=0, help_text='Quiz 1 Score', null=True),
        ),
    ]
