# Generated by Django 3.1.5 on 2022-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0053_auto_20220718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Quiz_1_Score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
