# Generated by Django 2.1.5 on 2022-07-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0054_auto_20220718_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='file',
            field=models.FileField(default='training_name.csv', help_text='Upload only CSV file with a nanme training_name.csv. Eg PMP.csv', unique=True, upload_to=''),
        ),
    ]
